<div id="main">

	<div id="header">
		<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
			codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0"
			width="800" height="372" id="flash_header">
			<param name="allowScriptAccess" value="sameDomain" />
			<param name="movie" value="header.swf?button=<%=page%>" />
			<param name="quality" value="high" />
			<param name="menu" value="false" />
			<param name="mode" value="transparent" />

			<embed src="header.swf?button=<%=page%>" quality="high"
				width="800" height="372" name="flash_header" allowScriptAccess="sameDomain"
				type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" mode="transparent"/>
		</object>
	</div>
		
	<div id="middle">